export const odishaDistricts = [
  "Angul",
  "Balangir",
  "Balasore",
  "Bargarh",
  "Bhadrak",
  "Boudh",
  "Cuttack",
  "Deogarh",
  "Dhenkanal",
  "Gajapati",
  "Ganjam",
  "Jagatsinghpur",
  "Jajpur",
  "Jharsuguda",
  "Kalahandi",
  "Kandhamal",
  "Kendrapara",
  "Kendujhar",
  "Khordha",
  "Koraput",
  "Malkangiri",
  "Mayurbhanj",
  "Nabarangpur",
  "Nayagarh",
  "Nuapada",
  "Puri",
  "Rayagada",
  "Sambalpur",
  "Subarnapur",
  "Sundargarh",
];

// export const plotData = [
//   {
//     id: 1,
//     code: "Chhendipada Jangal1005/322",
//     village: "Chhendipada Jangal",
//     sl: 1,
//     khataNo: "1005/322",
//     plotNo1: "1994",
//     plotNo2: "1994",
//     tenant: "Abhin Ch. Besan",
//     kissam: "Taila",
//     rorArea: 0.073,
//     occupiedArea: 0.0403,
//     remarks: "PART",
//     yadast: "10th Min",
//     bmv: "",
//     ses: 3300000,
//   },
//   {
//     id: 2,
//     code: "Chhendipada Jangal912",
//     village: "Chhendipada Jangal",
//     sl: 2,
//     khataNo: "912",
//     plotNo1: "1995",
//     plotNo2: "1995",
//     tenant: "Sanand Behera",
//     kissam: "Taila",
//     rorArea: 0.0565,
//     occupiedArea: 0.0008,
//     remarks: "PART",
//     yadast: "10th Min",
//     bmv: "",
//     ses: 3300000,
//   },
//   {
//     id: 3,
//     code: "Chhendipada Jangal913",
//     village: "Chhendipada Jangal",
//     sl: 3,
//     khataNo: "913",
//     plotNo1: "1999",
//     plotNo2: "1999",
//     tenant: "Sananda Behera & others",
//     kissam: "Taila",
//     rorArea: 0.126,
//     occupiedArea: 0.1173,
//     remarks: "PART",
//     yadast: "10th Min",
//     bmv: "",
//     ses: 3300000,
//   },
//   {
//     id: 4,
//     code: "Chhendipada Jangal912",
//     village: "Chhendipada Jangal",
//     sl: 4,
//     khataNo: "912",
//     plotNo1: "2000",
//     plotNo2: "2000",
//     tenant: "Sananda Behera",
//     kissam: "SAJS-III",
//     rorArea: 0.038,
//     occupiedArea: 0.0295,
//     remarks: "PART",
//     yadast: "10th Min",
//     bmv: "",
//     ses: 3300000,
//   },
//   {
//     id: 5,
//     code: "Chhendipada Jangal203",
//     village: "Chhendipada Jangal",
//     sl: 5,
//     khataNo: "203",
//     plotNo1: "2001",
//     plotNo2: "2001",
//     tenant: "Gobinda Behera",
//     kissam: "SAJS-III",
//     rorArea: 0.0405,
//     occupiedArea: 0.0032,
//     remarks: "PART",
//     yadast: "10th Min",
//     bmv: "",
//     ses: 3300000,
//   },
//   {
//     id: 6,
//     code: "Chhendipada Jangal348",
//     village: "Chhendipada Jangal",
//     sl: 6,
//     khataNo: "348",
//     plotNo1: "2084",
//     plotNo2: "2084",
//     tenant: "Dasarathi Sahu & Others",
//     kissam: "Patita",
//     rorArea: 0.665,
//     occupiedArea: 0.2042,
//     remarks: "PART",
//     yadast: "10th Min",
//     bmv: "",
//     ses: 3300000,
//   },
//   {
//     id: 7,
//     code: "Chhendipada Jangal348",
//     village: "Chhendipada Jangal",
//     sl: 7,
//     khataNo: "348",
//     plotNo1: "2088",
//     plotNo2: "2088",
//     tenant: "Dasarathi Sahu & Others",
//     kissam: "Taila",
//     rorArea: 0.1,
//     occupiedArea: 0.1,
//     remarks: "",
//     yadast: "10th Min",
//     bmv: "",
//     ses: 3300000,
//   },
//   {
//     id: 8,
//     code: "Chhendipada Jangal805",
//     village: "Chhendipada Jangal",
//     sl: 8,
//     khataNo: "805",
//     plotNo1: "2089",
//     plotNo2: "2089",
//     tenant: "Rabindra Pradhan",
//     kissam: "Taila",
//     rorArea: 0.044,
//     occupiedArea: 0.044,
//     remarks: "",
//     yadast: "10th Min",
//     bmv: "",
//     ses: 3300000,
//   },
//   {
//     id: 9,
//     code: "Chhendipada Jangal805",
//     village: "Chhendipada Jangal",
//     sl: 9,
//     khataNo: "805",
//     plotNo1: "2091",
//     plotNo2: "2091",
//     tenant: "Rabindra Pradhan",
//     kissam: "Taila",
//     rorArea: 0.03,
//     occupiedArea: 0.0199,
//     remarks: "PART",
//     yadast: "10th Min",
//     bmv: "",
//     ses: 3300000,
//   },
//   {
//     id: 10,
//     code: "Handigora383",
//     village: "Handigora",
//     sl: 3527,
//     khataNo: "383",
//     plotNo1: "47",
//     plotNo2: "47",
//     tenant: "Sebaka sahu & others",
//     kissam: "Taila",
//     rorArea: 0.0835,
//     occupiedArea: 0.0682,
//     remarks: "Part",
//     yadast: "Extra Area",
//     bmv: "",
//     ses: null,
//   },
//   {
//     id: 11,
//     code: "Handigora327",
//     village: "Handigora",
//     sl: 3528,
//     khataNo: "327",
//     plotNo1: "70",
//     plotNo2: "70",
//     tenant: "Rajkishore Sahu & others",
//     kissam: "Patita",
//     rorArea: 0.178,
//     occupiedArea: 0.177,
//     remarks: "Part",
//     yadast: "Extra Area",
//     bmv: "",
//     ses: null,
//   },
//   {
//     id: 12,
//     code: "Handigora407/352",
//     village: "Handigora",
//     sl: 3529,
//     khataNo: "407/352",
//     plotNo1: "70/2965",
//     plotNo2: "2965",
//     tenant: "Brajasundar Sahu",
//     kissam: "Taila",
//     rorArea: 0.009,
//     occupiedArea: 0.009,
//     remarks: "",
//     yadast: "Extra Area",
//     bmv: "",
//     ses: null,
//   },
//   {
//     id: 13,
//     code: "Handigora407/349",
//     village: "Handigora",
//     sl: 3530,
//     khataNo: "407/349",
//     plotNo1: "70/3764",
//     plotNo2: "3764",
//     tenant: "Raj Kishore Sahu",
//     kissam: "Taila",
//     rorArea: 0.0085,
//     occupiedArea: 0.0085,
//     remarks: "",
//     yadast: "Extra Area",
//     bmv: "",
//     ses: null,
//   },
//   {
//     id: 14,
//     code: "Handigora407/350",
//     village: "Handigora",
//     sl: 3531,
//     khataNo: "407/350",
//     plotNo1: "70/3767",
//     plotNo2: "3767",
//     tenant: "Bhajamana Sahu",
//     kissam: "Taila",
//     rorArea: 0.0085,
//     occupiedArea: 0.0085,
//     remarks: "",
//     yadast: "Extra Area",
//     bmv: "",
//     ses: null,
//   },
//   {
//     id: 15,
//     code: "Handigora407/351",
//     village: "Handigora",
//     sl: 3532,
//     khataNo: "407/351",
//     plotNo1: "70/3770",
//     plotNo2: "3770",
//     tenant: "Kunjabihari Sahu",
//     kissam: "Taila",
//     rorArea: 0.0085,
//     occupiedArea: 0.0085,
//     remarks: "",
//     yadast: "Extra Area",
//     bmv: "",
//     ses: null,
//   },
//   {
//     id: 16,
//     code: "Handigora284",
//     village: "Handigora",
//     sl: 3533,
//     khataNo: "284",
//     plotNo1: "71",
//     plotNo2: "71",
//     tenant: "Bhubaneswar Dehury & others",
//     kissam: "Taila",
//     rorArea: 0.7295,
//     occupiedArea: 0.7295,
//     remarks: "",
//     yadast: "Extra Area",
//     bmv: "",
//     ses: null,
//   },
//   {
//     id: 17,
//     code: "Handigora407/352",
//     village: "Handigora",
//     sl: 3534,
//     khataNo: "407/352",
//     plotNo1: "71/2966",
//     plotNo2: "2966",
//     tenant: "Brajasundar Sahu",
//     kissam: "SAJS-II",
//     rorArea: 0.021,
//     occupiedArea: 0.021,
//     remarks: "",
//     yadast: "Extra Area",
//     bmv: "",
//     ses: null,
//   },
//   {
//     id: 18,
//     code: "Handigora407/349",
//     village: "Handigora",
//     sl: 3535,
//     khataNo: "407/349",
//     plotNo1: "71/3765",
//     plotNo2: "3765",
//     tenant: "Raj Kishore Sahu",
//     kissam: "SAJS-II",
//     rorArea: 0.0215,
//     occupiedArea: 0.0215,
//     remarks: "",
//     yadast: "Extra Area",
//     bmv: "",
//     ses: null,
//   },
//   {
//     id: 19,
//     code: "Handigora407/350",
//     village: "Handigora",
//     sl: 3536,
//     khataNo: "407/350",
//     plotNo1: "71/3768",
//     plotNo2: "3768",
//     tenant: "Bhajamana Sahu",
//     kissam: "SAJS-II",
//     rorArea: 0.0215,
//     occupiedArea: 0.0215,
//     remarks: "",
//     yadast: "Extra Area",
//     bmv: "",
//     ses: null,
//   },
//   {
//     id: 20,
//     code: "Handigora407/351",
//     village: "Handigora",
//     sl: 3537,
//     khataNo: "407/351",
//     plotNo1: "71/3771",
//     plotNo2: "3771",
//     tenant: "Kunjabihari Sahu",
//     kissam: "SAJS-II",
//     rorArea: 0.0215,
//     occupiedArea: 0.0215,
//     remarks: "",
//     yadast: "Extra Area",
//     bmv: "",
//     ses: null,
//   },
//   {
//     id: 21,
//     code: "Handigora224",
//     village: "Handigora",
//     sl: 3538,
//     khataNo: "224",
//     plotNo1: "72",
//     plotNo2: "72",
//     tenant: "Prahlada Dehury& others",
//     kissam: "Taila",
//     rorArea: 0.79,
//     occupiedArea: 0.7795,
//     remarks: "Part",
//     yadast: "Extra Area",
//     bmv: "",
//     ses: null,
//   },
// ];

export const projectVillageKhataMap = {
  "GMDC - Baitarani-West Coal Block": {
    "Chhendipada Jangal": ["Khata-101", "Khata-102", "Khata-103"],
    Handigora: ["Khata-201", "Khata-202"],
  },
};

 export const sections = {
    "Basic Information": [
      "ses_survey_no",
      "la_case_file_no",
      "date_of_award",
      "village_name",
      "tahasil_name",
      "ri_circle_name",
      "thana_no",
      "khata_no",
      "plot_no",
      "kissam_of_land",
      "land_category",
      "priority_urgency",
      "land_use_plan",
      "lo13_remarks",
      "la21_remarks",
    ],
    "Tenant Information": [
      "name_of_recorded_tenant",
      "name_of_present_tenant",
      "present_address",
      "displaced_affected_person",
    ],
    "Land Details": [
      "land_area_total_acres",
      "land_area_total_hectares",
      "land_area_acquired_acres",
      "land_area_acquired_hectares",
      "market_value_per_acre",
      "basic_land_value",
      "land_value_with_mf",
    ],
    "Compensation Details": [
      "no_of_trees",
      "total_value_of_trees",
      "no_of_house",
      "value_of_house",
      "details_of_other_structures",
      "value_of_other_structures",
      "total_value",
      "solatium_100",
      "additional_12_percent",
      "total_compensation",
      "apportionment_amount",
    ],
    "Bank & Personal Details": [
      "bank_account_no",
      "bank_name",
      "branch_ifsc",
      "aadhaar_no",
      "pan_no",
      "age",
      "caste",
      "marital_status",
      "education",
      "occupation",
      "annual_income",
      "skill_acquired",
      "affidavit_details",
    ],
    "Family Details": [
      "family_major_male",
      "family_major_female",
      "family_minor_male",
      "family_minor_female",
      "family_major_transgender",
      "family_minor_transgender",
      "persons_with_disability",
      "family_with_orphan_members",
      "legal_heir_certificate_no",
    ],
    "Land Case Details": [
      "land_case_no",
      "land_case_date",
      "land_case_type",
      "land_case_status",
      "land_case_action",
    ],
    "R&R Assistance": [
      "rr_employment",
      "rr_cash_in_lieu",
      "rr_training_skill_upgradation",
      "rr_self_employment",
      "rr_special_allowance_st_ntfp",
      "rr_homestead_allotment",
      "rr_house_building_assistance",
      "rr_constructed_by",
      "rr_transit_shed",
      "rr_transport_allowance",
      "rr_maintenance_allowance",
      "rr_multiple_displacement_allowance",
      "rr_exgratia",
      "rr_other_benefits",
    ],
    "Grievance Details": [
      "grievance_no",
      "grievance_date",
      "grievance_subject",
      "grievance_status",
      "grievance_action",
    ],
    "Tribunal & Revenue": [
      "tribunal",
      "tribunal_deposit_date",
      "tribunal_amount",
      "premium",
      "ground_rent",
      "cess",
      "incidental_charges",
      "total",
      "abatement",
    ],
  };
export const getTypeName = (type) => {
  switch (Number(type)) {
    case 1:
      return "Pvt Land";
    case 2:
      return "Govt Land";
    case 3:
      return "Forest Land";
    default:
      return "-";
  }
};

// export const documentList = [
//   "Order Sheet",
//   "Notice by GMDC",
//   "Attendance sheet",
//   "Consent Form",
//   "Genealogy Sheet",
//   "Legal Heir Certificate",
//   "Yadast Register Copy",
//   "Self-Attested RoR",
//   "Certified copy of RoR",
//   "Patta original",
//   "Encumbrance Certificate",
//   "Rent Receipt",
//   "Trace Map",
//   "Application to Claim for lands compensation",
//   "Calculation of Compensation",
//   "Form 9A",
//   "Form 9A (Sample photo if any)",
//   "Form 9B",
//   "Form 9B (Sample photo if any)",
//   "Form 9C",
//   "Form 9C (Sample photo if any)",
//   "Land Acquisition Award",
//   "Indemnity Bond",
//   "Physical Possession certificate (Bond paper)",
//   "Apportionment Affidavit, if applicable",
//   "Affidavit any other legal issues",
//   "Aadhaar / Voter Card copy",
//   "PAN proof",
//   "Bank Account Passbook/Cancel Cheque copy",
//   "Electronic Fund Transfer Form",
//   "Receipt of Compensation-80%",
//   "Receipt of Compensation-20%",
//   "Payment Voucher-80%",
//   "Payment Voucher-20%",
//   "Photo of Physical Possession",
// ].map((doc) => ({
//   name: `${doc}.pdf`, // add .pdf to each
//   url: null, // placeholder, updated when file is uploaded
// }));
